name: qip_triagem
description: QIP - Questionário Interativo Psicopatológico.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter  
  just_audio: ^0.9.37
  #audioplayers: ^6.0.0
  flutter_colorpicker: ^1.0.3        
  flutter_modular: ^6.3.2
  hive: ^2.2.3
  hive_generator: ^2.0.1
  hive_flutter: ^1.1.0  
  #http: ^1.1.0
  #card_settings: ^3.5.0
  #card_settings:
  #  path: assets/card_settings
  brasil_fields: ^1.14.3
  intl: ^0.19.0
  #pattern_formatter: ^3.0.0
  collection: ^1.18.0
  rx_notifier: ^2.3.0
  #image_size_getter: ^2.1.2
  cupertino_icons: ^1.0.6
  dio: ^5.4.2+1
  super_sliver_list: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/assinatura_resia.png
    - assets/assinatura_keiji.png
    - assets/arvore_free.png
    - assets/olho1.png
    - assets/olho2.png
    - assets/olho3.png
    - assets/olho4.png
    - assets/olho5.png
    - assets/olho6.png
    - assets/olho7.png
    - assets/olho8.png
    - assets/olho9.png
    - assets/olho10.png
    - assets/olho11.png
    - assets/olho12.png
    - assets/olho13.png
    - assets/olho14.png                                
    - assets/intel_1.png
    - assets/intel_1a.png
    - assets/intel_1b.png
    - assets/intel_1c.png
    - assets/intel_1d.png
    - assets/intel_1e.png
    - assets/intel_1f.png
    - assets/questao32.png
    - assets/Ebbinghaus.png
    - assets/questao45leaonovo.png
    - assets/questao45controlegame.png
    - assets/questao45viajar.png
    - assets/questao45trabalhador.png    
    - assets/questao45livros.png
    - assets/questao45coquetel.png
    - assets/questao45passaro.png
    - assets/questao45gato.png
    - assets/questao45cachorro.png
    - assets/questao45bombons.png
    - assets/questao45cafe.png
    - assets/questao45carro.png
    - assets/questao45casa.png
    - assets/questao45cerveja.png
    - assets/questao45cocacola.png
    - assets/questao45humburgue.png
    - assets/questao45passaro.png
    - assets/questao48.png
    - assets/CORREDOR.png
    - assets/PAPAI NOEL.png
    - assets/circo.png
    - assets/chuteira.png
    - assets/NUMERO8.png
    - assets/reciclagem.png
    - assets/seisimagens.png
    - assets/emoji_sempre_atrasado.png
    - assets/emoji_poderoso.png
    - assets/emoji_otimista.png
    - assets/emoji_em_panico.png
    - assets/emoji_indeciso.png
    - assets/emoji_triste.png
    - assets/emoji_entediado.png
    - assets/emoji_pessimista.png
    - assets/emoji_reflexivo.png
    - assets/emoji_confiante.png
    - assets/emoji_forte.png
    - assets/emoji_nojo.png
    - assets/emoji_esperancoso.png
    - assets/emoji_pura_alegria.png
    - assets/emoji_burro.png
    - assets/emoji_surpreso.png
    - assets/emoji_feliz.png
    - assets/emoji_velho.png
    - assets/emoji_frustrado.png
    - assets/emoji_ansioso.png
    - assets/emoji_emocionado.png
    - assets/emoji_em_paz.png
    - assets/emoji_inteligente.png
    - assets/emoji_preocupado.png    
    - assets/emoji_apaixonado.png
    - assets/emoji_desesperado.png
    - assets/emoji_envergonhado.png
    - assets/emoji_abencoado.png
    - assets/emoji_impulsivo.png
    - assets/emoji_amado.png
    - assets/emoji_confuso.png
    - assets/emoji_sem_forcas.png
    - assets/emoji_sonolento.png
    - assets/emoji_gordo.png
    - assets/emoji_sem_paciencia.png
    - assets/emoji_com_ciumes.png   
    - assets/emoji_com_raiva.png
    - assets/emoji_silenciado.png
    - assets/emoji_desanimado.png       
    - assets/emoji_com_gratidao.png
    - assets/emoji_fraude.png
    - assets/emoji_agressivo.png
    - assets/emoji_desequilibrado.png
    - assets/emoji_comendo_muito.png
    - assets/emoji_fumando_muito.png
    - assets/emoji_jesus.png
    - assets/emoji_bebendo_muito.png
    - assets/emoji_animado.png
    - assets/audios/aguacorrente-edited_v2.mp3
    - assets/audios/chuva_edited.mp3
    - assets/audios/chuva.mp3
    - assets/audios/chuva_edited.wav
    - assets/audios/quatro_palavras.mp3
    - assets/audios/dez_palavras.mp3
    - assets/intel_2.png
    - assets/intel_2a.png
    - assets/intel_2b.png
    - assets/intel_2c.png
    - assets/intel_2d.png
    - assets/intel_2e.png
    - assets/intel_2f.png
    - assets/five_errors1.jpg
    - assets/five_errors2.jpg
    - assets/arvore_circulos.png
    - assets/montandocerebro.png