name: just_audio_web
description: Web platform implementation of just_audio. This implementation is endorsed and therefore doesn't require a direct dependency.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
homepage: https://github.com/ryanheise/just_audio/tree/master/just_audio_web
version: 0.4.9

flutter:
  plugin:
    platforms:
      web:
        pluginClass: JustAudioPlugin
        fileName: just_audio_web.dart

dependencies:
  web: ^0.5.1
  just_audio_platform_interface:
    path: ../just_audio_platform_interface
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"
