
from openpyxl import Workbook

comentarios = {
    'B': "Momento em que começou a responder o Questionário\n",
    'B': "Momento em que começou a responder o Questionário\n",
    'C': "Confirmação do Usuário que está disposto a responder o Questionário\n",
    'D': "Momento em que começou a responder a tela 2 do Questionário\n",
    'E': "Resposta do usuário à pergunta: Que horas são neste instante?\n",
    'F': "Resposta do usuário à pergunta: Data de hoje?\n",
    'G': "Resposta do usuário à pergunta: Qual a sua Idade?\n",
    'H': "Resposta do usuário à pergunta: Qual o seu gênero?\n",
    'I': "Resposta do usuário à pergunta: Qual foi o sexo atribuído no seu nascimento?\n",
    'J': "Resposta do usuário à pergunta: Qual a sua Cor ou Raça ?\n",
    'K': "Resposta do usuário à pergunta: Quantos irmãos você tem?\n",
    'L': "Resposta do usuário à pergunta: Qual o seu estado civil?\n",
    'M': "Resposta do usuário à pergunta: Quantos filhos você tem?\n",
    'N': "Resposta do usuário à pergunta: Possui filhos(as) menores de 6 anos?\n",
    'O': "Resposta do usuário à pergunta: Qual é a Religião?\n",
    'P': "Resposta do usuário à pergunta: Qual a sua Escolaridade?\n",
    'Q': "Resposta do usuário à pergunta: Qual a sua Renda familiar mensal de sua casa (somatória)?\n",
    'R': "Momento em que começou a responder a tela 3 do Questionário\n",
    'S': "Momento em que começou a responder a tela 7 do Questionário\n",
    'T': "Resposta do usuário à pergunta: O que você viu na tela anterior?\n",
    'U': "Momento em que começou a responder a tela 10 do Questionário\n",
    'V': "Resposta do usuário à pergunta: O que você viu na tela anterior?\n",
    'W': "Momento em que começou a responder a tela 13 do Questionário\n",
    'X': "Resposta do usuário à pergunta: Qual foi a sequência correta dos números apresentados na tela anterior?\n",
    'Y': "Momento em que começou a responder a tela 15 do Questionário\n",
    'Z': "Resposta do usuário à pergunta: Qual foi a sequência correta dos números apresentados na tela anterior?\n",
    'AA': "Momento em que começou a responder a tela 17 do Questionário\n",
    'AB': "Resposta do usuário à pergunta: Qual foi a sequência correta dos números apresentados na tela anterior?\n",
    'AC': "Momento em que começou a responder a tela 19 do Questionário\n",
    'AD': "Resposta do usuário à pergunta: Qual foi a sequência correta dos números apresentados na tela anterior?\n",
    'AE': "Momento em que começou a responder a tela 21 do Questionário\n",
    'AF': "Resposta do usuário à pergunta: Qual foi a sequência correta dos números apresentados na tela anterior?\n",
    'AG': "Momento em que começou a responder a tela 23 do Questionário\n",
    'AH': "Resposta do usuário à pergunta: Qual foi a sequência correta dos números apresentados na tela anterior?\n",
    'AI': "Momento em que começou a responder a tela 25 do Questionário\n",
    'AJ': "O usuário deve selecione a palavra que melhor a descreve a imagem apresentada a ele.\n",
    'AK': "O usuário deve selecione a palavra que melhor a descreve a imagem apresentada a ele.\n",
    'AL': "O usuário deve selecione a palavra que melhor a descreve a imagem apresentada a ele.\n",
    'AM': "O usuário deve selecione a palavra que melhor a descreve a imagem apresentada a ele.\n",
    'AN': "O usuário deve selecione a palavra que melhor a descreve a imagem apresentada a ele.\n",
    'AO': "O usuário deve selecione a palavra que melhor a descreve a imagem apresentada a ele.\n",
    'AP': "O usuário deve selecione a palavra que melhor a descreve a imagem apresentada a ele.\n",
    'AQ': "O usuário deve selecione a palavra que melhor a descreve a imagem apresentada a ele.\n",
    'AR': "O usuário deve selecione a palavra que melhor a descreve a imagem apresentada a ele.\n",
    'AS': "O usuário deve selecione a palavra que melhor a descreve a imagem apresentada a ele.\n",
    'AT': "O usuário deve selecione a palavra que melhor a descreve a imagem apresentada a ele.\n",
    'AU': "O usuário deve selecione a palavra que melhor a descreve a imagem apresentada a ele.\n",
    'AV': "O usuário deve selecione a palavra que melhor a descreve a imagem apresentada a ele.\n",
    'AW': "O usuário deve selecione a palavra que melhor a descreve a imagem apresentada a ele.\n",
    'AX': "Momento em que começou a responder a tela 26 do Questionário\n",
    'AY': "Resposta do usuário à pergunta: Tem sentido muito medo de perder o controle ou enlouquecer?\n",
    'AZ': "Resposta do usuário à pergunta: Para impedir o ganho de peso, há uso de laxantes, diuréticos ou outros medicamentos; jejum, vômitos autoinduzidos, ou exercício físico em excesso?\n",
    'BA': "Resposta do usuário à pergunta: Sente medo intenso de ganhar peso ou de engordar, ao ponto de não comer?\n",
    'BB': "Resposta do usuário à pergunta: Há ingestão persistente de substâncias não nutritivas tais como doces e/ou chocolates, durante um período mínimo de um mês?\n",
    'BC': "Resposta do usuário à pergunta: Você se irrita fácil, de forma que seu humor muda facilmente durante o dia?\n",
    'BD': "Resposta do usuário à pergunta: Já teve ataques ou crises de medo intenso nos quais se sentiu muito mal?\n",
    'BE': "Momento em que começou a responder a tela 25 do Questionário\n",
    'BF': "O usuário deve selecione uma imagem que completa a imagem apresentada a ele.\n",
    'BG': "Momento em que começou a responder a tela 28 do Questionário\n",
    'AH': "Resposta do usuário à pergunta: Ultimamente tem arrancado o próprio cabelo de forma recorrente, resultando em perda de cabelo?\n",
    'AI': "Resposta do usuário à pergunta: Observou grande perda de interesse ou prazer em todas ou quase todas as atividades na maior parte do dia; sente-se triste, vazio, sem esperança?\n",
    'BJ': "Resposta do usuário à pergunta: Você se sente incomodado por pensamentos que surgem em sua mente, mesmo quando não os deseja, como o medo de estar exposto a germes, doenças ou sujeira, ou a necessidade de que tudo esteja alinhado de certa maneira?\n",
    'BK': "Resposta do usuário à pergunta: Você é incomodado por imagens indesejadas que surgem em sua mente, como cenas violentas e horríveis, ou conteúdo de natureza sexual?\n",
    'BL': "Resposta do usuário à pergunta: Percebo que sou uma pessoa especial e único/a? Espero que um dia as pessoas possam reconhecer meu valor e a diferença que faço na vida delas.\n",
    'BM': "Resposta do usuário à pergunta: Tende a se enxergar como alguém socialmente incapaz, sem atrativos pessoais ou inferior aos outros?\n",
    'BN': "Resposta do usuário à pergunta: Possui dificuldade em iniciar projetos ou fazer as coisas sozinho (por falta de autoconfiança, em vez de falta de motivação ou energia)?\n",
    'BO': "Momento em que começou a responder a tela 29 do Questionário\n",
    'BP': "Usuário precisa completar a sequencia: 2, 4, 8, 16, ?\n",
    'BQ': "Usuário precisa completar a sequencia: 1, 3, 9, ?\n",    
    'BR': "Usuário precisa completar a sequencia: 3, 7, 11, 15, ?\n", 
    'BS': "Usuário precisa completar a sequencia: 32, 16, 8, ? \n", 
    'BT': "Momento em que começou a responder a tela 30 do Questionário\n",
    'BU': "Resposta do usuário à pergunta: Forme uma frase que faça sentido colocando as palavras em ordem correta:\n",
    'BV': "Momento em que começou a responder a tela 31 do Questionário\n",
    'BW': "Resposta do usuário à pergunta: Sente algo estranho dentro do seu corpo, e/ou movimentos, como se levasse um empurrão?\n",
    'BX': "Resposta do usuário à pergunta: Sente como se alguém lhe tocasse, beliscassem, batessem ou beijassem seu corpo?\n",
    'BY': "Resposta do usuário à pergunta: Possui a sensação de falta de controle durante a alimentação; não consegue parar de comer ou controlar a quantidade que está ingerindo?\n",
    'BZ': "Resposta do usuário à pergunta: Sente-se descansado e preparado para mais um dia, mesmo com apenas 3 horas de sono?\n",
    'CA': "Resposta do usuário à pergunta: Você com frequência tem dificuldade em manter-se concentrado durante a realização de tarefas ou atividades?\n",
    'CB': "Resposta do usuário à pergunta: Muitas vezes responde precipitadamente antes que as perguntas tenham sido completadas.\n",
    'CC': "Momento em que começou a responder a tela 32 do Questionário\n",
    'CD': "Resposta do usuário à pergunta: Cidade onde você está agora?\n",
    'CE': "Resposta do usuário à pergunta: Estado onde você está agora?\n",
    'CF': "Momento em que começou a responder a tela 33 do Questionário\n",
    'CG': "Resposta do usuário à pergunta: Selecione qual o período do dia atual?\n",
    'CH': "Momento em que começou a responder a tela 41 do Questionário\n",
    'CI': "Resposta do usuário à pergunta: Diariamente, há momentos em que você sente como se o chão oscilasse?\n",
    'CJ': "Resposta do usuário à pergunta: Durante o dia há vários momentos em que você se sente irritado(a) e impaciente?\n",
    'CK': "Resposta do usuário à pergunta: Diariamente, há momentos em que você se sente muito feliz, irradiante?\n",
    'CL': "Resposta do usuário à pergunta: Durante o dia há vários momentos em que você se sente triste e/ou melancólico(a)?\n",
    'CM': "Resposta do usuário à pergunta: Tem notado(a) muita preocupação com um ou mais defeitos ou falhas percebidas na aparência física que não são observáveis ou que parecem leves para os outros.\n",
    'CN': "Resposta do usuário à pergunta: Você com frequência mexe de forma irrequieta as mãos e os pés ou remexe-se na cadeira quando está sentado(a)?\n",
    'CO': "Resposta do usuário à pergunta: Exibe dificuldade em concordar com as ideias de outras pessoas, demonstrando inflexibilidade e rigidez tanto em relação a si mesmo quanto aos outros.\n",
    'CP': "Momento em que começou a responder a tela 42 do Questionário\n",
    'CQ': "Resposta do usuário à pergunta: Encontre as 6 imagens que apareceção anteriormente aqui?\n",
    'CR': "Momento em que começou a responder a tela 43 do Questionário\n",
    'CS': "Resposta do usuário à pergunta: Encontrar-se com um ente querido falecido.\n",
    'CT': "Resposta do usuário à pergunta: Ver uma pessoa nua\n",
    'CU': "Resposta do usuário à pergunta: Saber como desempenhar tarefas cotidianas sem ser prejudicado por pensamentos incessantes que me limitam.\n",
    'CV': "Resposta do usuário à pergunta: Voltar na minha infância e recomeçar tudo\n",
    'CW': "Resposta do usuário à pergunta: Voltar na minha adolescência e recomeçar tudo\n",
    'CX': "Resposta do usuário à pergunta: Saber se meu namorado (a) ou esposo (a) está me traindo\n",
    'CY': "Resposta do usuário à pergunta: Saber como poderia ser o futuro da minha família e ajudá-los\n",
    'CZ': "Resposta do usuário à pergunta: Desaparecer no tempo e espaço, ao entrar pela fenda\n",
    'DA': "Resposta do usuário à pergunta: Saber se estarei vivo daqui 5 anos.\n",
    'DB': "Resposta do usuário à pergunta: Saber quem é minha alma gêmea.\n",
    'DC': "Resposta do usuário à pergunta: Ver meu futuro profissional.\n",
    'DD': "Resposta do usuário à pergunta: Testemunhar avanços tecnológicos futuros.\n",
    'DE': "Resposta do usuário à pergunta: Presenciar um evento histórico de grande relevância, como a construção das pirâmides do Egito, a Grande Muralha da China, a era dos dinossauros, ou a criação de alguma das invenções de Albert Einstein ou Leonardo da Vinci, por exemplo.\n",
    'DF': "Resposta do usuário à pergunta: Saber se ficarei rico(a)\n",
    'DG': "Resposta do usuário à pergunta: Saber como faço para dormir a noite toda.\n",
    'DH': "Resposta do usuário à pergunta: Saber como fazer meu cônjuge e/ou filho(a) a realizar tarefas e tomar decisões em suas vidas de acordo com meus valores e princípios.\n",
    'DI': "Resposta do usuário à pergunta: Saber como desaparecer minha dor e sofrimento existencial.\n",
    'DJ': "Momento em que começou a responder a tela 44 do Questionário\n",
    'DK': "Resposta do usuário à pergunta: Percebe-se impulsivo(a) e de forma abusiva; p. ex., gastos exagerados, sexo com desconhecidos, abuso de substâncias, dirigir de forma perigosa/irresponsável e/ou atos repetitivos de autolesão?\n",
    'DL': "Resposta do usuário à pergunta: Tem dificuldade em terminar o que começa?\n",
    'DM': "Resposta do usuário à pergunta: Quando você conta uma história que aconteceu, na maioria das vezes você exagera e dramatiza alguns detalhes?\n",
    'DN': "Resposta do usuário à pergunta: Já testemunhou e/ou ainda é exposto(a) de forma repetida ou extrema a detalhes aversivos do evento traumático?\n",
    'DO': "Resposta do usuário à pergunta: Você apresenta explosões de raiva recorrente, manifestadas por meio da linguagem (como insultos dirigidos a outras pessoas) ou através de ações (como agressão física)?\n",
    'DP': "Resposta do usuário à pergunta: Você está tendo insônia praticamente todos os dias?\n",
    'DQ': "Momento em que começou a responder a tela 47 do Questionário\n",
    'DR': "Resposta do usuário à pergunta: Qual das opções corresponde ao som escutado?\n",        
    'DS': "Momento em que começou a responder a tela 48 do Questionário\n",
    'DT': "Resposta do usuário à pergunta: Selecione qual alternativa corresponde ao que você vê na imagem acima.\n",            
    'DU': "Momento em que começou a responder a tela 49 do Questionário\n",
    'DV': "Resposta do usuário à pergunta: O que você deseja desenhar?\n",  
    'DW': "Resposta do usuário à pergunta: O desenho:\n",           
    'DX': "Momento em que começou a responder a tela 50 do Questionário\n",
    'DY': "Resposta do usuário à pergunta: Você tem sentido mais fadiga ou perda de energia quase todos os dias?\n",
    'DZ': "Resposta do usuário à pergunta: Você vivenciou algum evento traumático?\n",
    'EA': "Resposta do usuário à pergunta: Você tem escutado Zumbido no ouvido?\n",
    'EB': "Resposta do usuário à pergunta: Você tem dificuldades em jogar fora objetos usados ou sem valor, mesmo quando não têm valor sentimental. Ultimamente guarda muitas coisas, papeis, recibos, com a ideia de que poderá precisar algum dia?\n",
    'EC': "Resposta do usuário à pergunta: Você apresenta comportamentos repetitivos (p. ex., lavar as mãos, organizar, verificar) ou atos mentais (p. ex., orar, contar ou repetir palavras em silêncio).\n",
    'ED': "Resposta do usuário à pergunta: Você se sente incomodado por impulsos como machucar alguém que você ama, mesmo quando não deseja fazê-lo?\n",
    'EE': "Resposta do usuário à pergunta: Você tem visto algo estranho como figuras, sombras, fogo, fantasmas, demônios, pessoas estranhas ou algo do tipo, no seu dia a dia?\n",
    'EF': "Momento em que começou a responder a tela 51 do Questionário\n",
    'EG': "Resposta do usuário à pergunta: Encontre os 5 erros?\n",  
    'EH': "Momento em que começou a responder a tela 52 do Questionário\n",
    'EI': "Resposta do usuário à pergunta: Nos últimos meses, você tem ouvido vozes de pessoas estranhas?\n",
    'EJ': "Resposta do usuário à pergunta: Ultimamente, você tem ouvido vozes que são seus próprios pensamentos sendo expressos em voz alta?\n",
    'EK': "Resposta do usuário à pergunta: Alguém tem tentado envenená-lo(a)?\n",
    'EL': "Resposta do usuário à pergunta: Você tem dificuldade para relaxar? Está sempre ocupado(a)?\n",
    'EM': "Resposta do usuário à pergunta: Você vem apresentando sensações de falta de ar ou sufocamento?\n",
    'EN': "Resposta do usuário à pergunta: Você está vivenciando um estado de luto prolongado e persistente, que se estende por um período superior a 12 meses, caracterizado por uma intensa saudade, preocupação e apatia em relação ao futuro?\n",
    'EO': "Resposta do usuário à pergunta: Você tem medo de ser demitido(a) o tempo todo?\n",     
    'EP': "Momento em que começou a responder a tela 53 do Questionário\n",
    'EQ': "Resposta do usuário à pergunta: Qual das imagens abaixo completa a sequência a seguir?\n", 
    'ER': "Momento em que começou a responder a tela 54 do Questionário\n",
    'ES': "Resposta do usuário à pergunta: Você vive com medo de decepcionar as pessoas?\n",
    'ET': "Resposta do usuário à pergunta: Você tem-se irritado com mais facilidade que antes?\n",
    'EU': "Resposta do usuário à pergunta: Nos últimos meses você sente dificuldades de parar de se preocupar?\n",
    'EV': "Resposta do usuário à pergunta: Você pensa muitas coisas ao mesmo tempo?\n",
    'EW': "Resposta do usuário à pergunta: Você sente dificuldade em se concentrar?\n",
    'EX': "Resposta do usuário à pergunta: Evita realizar atividades profissionais ou estudantis que impliquem contato interpessoal, pois tem muito medo de críticas, desaprovação ou rejeição?\n",
    'EY': "Resposta do usuário à pergunta: Você não acha que tem fraquezas e muito menos evita ambientes, pois consegue tudo o que quer?\n",    
    'EZ': "Momento em que começou a responder a tela 57 do Questionário\n",
    'FA': "Resposta do usuário à pergunta: coquetel\n", 
    'FB': "Resposta do usuário à pergunta: humburgue\n",
    'FC': "Resposta do usuário à pergunta: casa\n",
    'FD': "Resposta do usuário à pergunta: gato\n",
    'FE': "Resposta do usuário à pergunta: trabalhador\n",
    'FF': "Resposta do usuário à pergunta: carro\n",
    'FG': "Resposta do usuário à pergunta: cachorro\n",
    'FH': "Resposta do usuário à pergunta: passaro\n",
    'FI': "Resposta do usuário à pergunta: cerveja\n",
    'FJ': "Resposta do usuário à pergunta: cocacola\n",
    'FK': "Resposta do usuário à pergunta: cafe\n",
    'FL': "Resposta do usuário à pergunta: bombons\n",
    'FM': "Resposta do usuário à pergunta: viajar\n",
    'FN': "Resposta do usuário à pergunta: livros\n",
    'FO': "Resposta do usuário à pergunta: leao\n",
    'FP': "Resposta do usuário à pergunta: controlegame\n",
    'FQ': "Momento em que começou a responder a tela 58 do Questionário\n",
    'FR': "Resposta do usuário à pergunta: Você acredita que precisa fazer as coisas de forma perfeita, caso contrário não será aceito (a)?\n",
    'FS': "Resposta do usuário à pergunta: Você acredita que as pessoas estão julgando suas atitudes e comportamentos, mesmo que não estejam dizendo?\n",
    'FT': "Resposta do usuário à pergunta: Você tem ideias negativas, como pensar em morrer?\n",
    'FU': "Resposta do usuário à pergunta: Você se sente inadequado (a) inquieto (a) e conversa de forma excessiva?\n",
    'FV': "Resposta do usuário à pergunta: Você costuma adiar ou evitar fazer as coisas até o último minuto? Possui o perfil de procrastinar?\n",
    'FW': "Resposta do usuário à pergunta: Tem relutado em delegar tarefas ou de trabalhar com outras pessoas, pois precisa estar no controle de tudo.\n",
    'FX': "Resposta do usuário à pergunta: Você percebe que se esforça de forma intensa para evitar ser abandonado (a)?\n", 
    'FY': "Momento em que começou a responder a tela 59 do Questionário\n",
    'FZ': "Resposta do usuário à pergunta: Qual das opções corresponde ao som escutado?\n", 
    'GA': "Momento em que começou a responder a tela 60 do Questionário\n",
    'GB': "Resposta do usuário à pergunta: Qual a emoção básica da imagem:\n", 
    'GC': "Resposta do usuário à pergunta: Qual a emoção básica da imagem:\n",
    'GD': "Resposta do usuário à pergunta: Qual a emoção básica da imagem:\n",
    'GE': "Resposta do usuário à pergunta: Qual a emoção básica da imagem:\n",
    'GF': "Resposta do usuário à pergunta: Qual a emoção básica da imagem:\n",
    'GG': "Resposta do usuário à pergunta: Qual a emoção básica da imagem:\n",
    'GH': "Momento em que começou a responder a tela 62 do Questionário\n",
    'GI': "Quando a resposta é o emoji: sempre_atrasado\n",
    'GJ': "Quando a resposta é o emoji: poderoso\n", 
    'GK': "Quando a resposta é o emoji: otimista\n", 
    'GL': "Quando a resposta é o emoji: em_panico\n", 
    'GM': "Quando a resposta é o emoji: indeciso\n", 
    'GN': "Quando a resposta é o emoji: triste\n", 
    'GO': "Quando a resposta é o emoji: entediado\n", 
    'GP': "Quando a resposta é o emoji: pessimista\n", 
    'GQ': "Quando a resposta é o emoji: reflexivo\n", 
    'GR': "Quando a resposta é o emoji: confiante\n", 
    'GS': "Quando a resposta é o emoji: forte\n", 
    'GT': "Quando a resposta é o emoji: nojo\n", 
    'GU': "Momento em que começou a responder a tela 63 do Questionário\n",
    'GV': "Quando a resposta é o emoji: esperancoso\n", 
    'GW': "Quando a resposta é o emoji: pura_alegria\n",
    'GX': "Quando a resposta é o emoji: burro\n", 
    'GY': "Quando a resposta é o emoji: surpreso\n", 
    'GZ': "Quando a resposta é o emoji: feliz\n", 
    'HA': "Quando a resposta é o emoji: velho\n", 
    'HB': "Quando a resposta é o emoji: frustrado\n", 
    'HC': "Quando a resposta é o emoji: ansioso\n", 
    'HD': "Quando a resposta é o emoji: emocionado\n", 
    'HE': "Quando a resposta é o emoji: em_paz\n", 
    'HF': "Quando a resposta é o emoji: inteligente\n", 
    'HG': "Quando a resposta é o emoji: preocupado\n", 
    'HH': "Momento em que começou a responder a tela 64 do Questionário\n",
    'HI': "Quando a resposta é o emoji: apaixonado\n", 
    'HJ': "Quando a resposta é o emoji: desesperado\n",
    'HK': "Quando a resposta é o emoji: envergonhado\n", 
    'HL': "Quando a resposta é o emoji: abencoado\n", 
    'HM': "Quando a resposta é o emoji: impulsivo\n", 
    'HN': "Quando a resposta é o emoji: amado\n", 
    'HO': "Quando a resposta é o emoji: confuso\n", 
    'HP': "Quando a resposta é o emoji: sem_forcas\n", 
    'HQ': "Quando a resposta é o emoji: sonolento\n", 
    'HR': "Quando a resposta é o emoji: gordo\n", 
    'HS': "Quando a resposta é o emoji: sem_paciencia\n", 
    'HT': "Quando a resposta é o emoji: com_ciumes\n",
    'HU': "Momento em que começou a responder a tela 65 do Questionário\n",
    'HV': "Quando a resposta é o emoji: com_raiva\n", 
    'HW': "Quando a resposta é o emoji: silenciado\n",
    'HX': "Quando a resposta é o emoji: desanimado\n", 
    'HY': "Quando a resposta é o emoji: com_gratidao\n", 
    'HZ': "Quando a resposta é o emoji: fraude\n", 
    'IA': "Quando a resposta é o emoji: agressivo\n", 
    'IB': "Quando a resposta é o emoji: desequilibrado\n", 
    'IC': "Quando a resposta é o emoji: comendo_muito\n", 
    'ID': "Quando a resposta é o emoji: fumando_muito\n", 
    'IE': "Quando a resposta é o emoji: jesus\n", 
    'IF': "Quando a resposta é o emoji: bebendo_muito\n", 
    'IG': "Quando a resposta é o emoji: animado\n",
    'IH': "Momento em que começou a responder a tela 66 do Questionário\n",
    'II': "Quando a resposta é o emoji: ABANDONO\n", 
    'IJ': "Quando a resposta é o emoji: ACOMETIDO(A)\n",
    'IK': "Quando a resposta é o emoji: AFEIÇÃO\n", 
    'IL': "Quando a resposta é o emoji: AMIUDAR\n", 
    'IM': "Quando a resposta é o emoji: ANTIPATIA\n", 
    'IN': "Quando a resposta é o emoji: APATIA\n", 
    'IO': "Quando a resposta é o emoji: APEGO\n", 
    'IP': "Quando a resposta é o emoji: APREENSÃO\n", 
    'IQ': "Quando a resposta é o emoji: ARQUEJO\n", 
    'IR': "Quando a resposta é o emoji: ATONIA\n", 
    'IS': "Quando a resposta é o emoji: AUTENTICIDADE\n", 
    'IT': "Quando a resposta é o emoji: AUTOCÍDIO\n",
    'IU': "Quando a resposta é o emoji: AUTOESTIMA\n", 
    'IV': "Quando a resposta é o emoji: BELEZA\n", 
    'IW': "Quando a resposta é o emoji: BONDADE\n", 
    'IX': "Quando a resposta é o emoji: COMPLACÊNCIA\n", 
    'IY': "Quando a resposta é o emoji: COMPULSÃO\n", 
    'IZ': "Quando a resposta é o emoji: CORAGEM\n", 
    'JA': "Quando a resposta é o emoji: DECÊNCIA\n", 
    'JB': "Quando a resposta é o emoji: DESAFETO\n", 
    'JC': "Quando a resposta é o emoji: DESÂNIMO\n", 
    'JD': "Quando a resposta é o emoji: DESARMONIA\n",
    'JE': "Quando a resposta é o emoji: DESTEMOR\n", 
    'JF': "Quando a resposta é o emoji: DIGNIDADE\n", 
    'JG': "Quando a resposta é o emoji: ELEGÂNCIA\n", 
    'JH': "Quando a resposta é o emoji: EMPATIA\n", 
    'JI': "Quando a resposta é o emoji: ESPERANÇA\n", 
    'JJ': "Quando a resposta é o emoji: ESTIMA\n", 
    'JK': "Quando a resposta é o emoji: ESTREITEZA\n", 
    'JL': "Quando a resposta é o emoji: EUFORIA\n", 
    'JM': "Quando a resposta é o emoji: FRACASSO\n", 
    'JN': "Quando a resposta é o emoji: FORTÚNIO\n", 
    'JO': "Quando a resposta é o emoji: FRAQUEZA\n", 
    'JP': "Quando a resposta é o emoji: FUGAZ\n", 
    'JQ': "Quando a resposta é o emoji: GENTILEZA\n", 
    'JR': "Quando a resposta é o emoji: GRATIDÃO\n", 
    'JS': "Quando a resposta é o emoji: HARMONIA\n", 
    'JT': "Quando a resposta é o emoji: HUMILDADE\n", 
    'JU': "Quando a resposta é o emoji: IMPOTÊNCIA\n", 
    'JV': "Quando a resposta é o emoji: IMPULSIVIDADE\n", 
    'JW': "Quando a resposta é o emoji: INAPETÊNCIA\n", 
    'JX': "Quando a resposta é o emoji: INDIFERENÇA\n",
    'JY': "Quando a resposta é o emoji: INDULGÊNCIA\n", 
    'JZ': "Quando a resposta é o emoji: INQUIETUDE\n", 
    'KA': "Quando a resposta é o emoji: INTELIGÊNCIA\n", 
    'KB': "Quando a resposta é o emoji: LETARGIA\n", 
    'KC': "Quando a resposta é o emoji: MÁGOA\n", 
    'KD': "Quando a resposta é o emoji: MANIA\n", 
    'KE': "Quando a resposta é o emoji: MELANCOLIA\n", 
    'KF': "Quando a resposta é o emoji: MORTE\n", 
    'KG': "Quando a resposta é o emoji: NOSTALGIA\n", 
    'KH': "Quando a resposta é o emoji: OBCECAÇÃO\n",
    'KI': "Quando a resposta é o emoji: OBSESSÃO\n", 
    'KJ': "Quando a resposta é o emoji: PERECÍVEL\n", 
    'KK': "Quando a resposta é o emoji: PERSISTÊNCIA\n", 
    'KL': "Quando a resposta é o emoji: PREOCUPAÇÃO\n", 
    'KM': "Quando a resposta é o emoji: PROSTRAÇÃO\n", 
    'KN': "Quando a resposta é o emoji: PRUDÊNCIA\n", 
    'KO': "Quando a resposta é o emoji: RUMINAÇÃO\n", 
    'KP': "Quando a resposta é o emoji: RAIVA\n", 
    'KQ': "Quando a resposta é o emoji: RANCOR\n", 
    'KR': "Quando a resposta é o emoji: SATISFAÇÃO\n",
    'KS': "Quando a resposta é o emoji: SIGILO\n", 
    'KT': "Quando a resposta é o emoji: SOLIDÃO\n", 
    'KU': "Quando a resposta é o emoji: SUICÍDIO\n", 
    'KV': "Quando a resposta é o emoji: TENACIDADE\n", 
    'KW': "Quando a resposta é o emoji: VIRTUDE\n", 
    'KX': "Momento em que começou a responder a tela 69 do Questionário\n",
    'KY': "Complete o que foi escutado no audio: chuva -\n", 
    'KZ': "Complete o que foi escutado no audio: criança -\n", 
    'LA': "Complete o que foi escutado no audio: - verão\n", 
    'LB': "Complete o que foi escutado no audio: mostro -\n", 
    'LC': "Complete o que foi escutado no audio: - água\n", 
    'LD': "Complete o que foi escutado no audio: dinheiro -\n", 
    'LE': "Complete o que foi escutado no audio: - pequeno\n", 
    'LF': "Complete o que foi escutado no audio: livro -\n", 
    'LG': "Complete o que foi escutado no audio: - móvel\n", 
    'LH': "Complete o que foi escutado no audio: Professor -\n",
    'LI': "Momento em que começou a responder a tela 70 do Questionário\n",
    'LJ': "Resposta do usuário à pergunta: Você se preocupa com a internet (pensa sobre atividades virtuais anteriores ou fica antecipando quando ocorrerá a próxima conexão)?\n",
    'LK': "Resposta do usuário à pergunta: Você sente necessidade de usar a internet por períodos cada vez maiores para se sentir satisfeito?\n",
    'LL': "Resposta do usuário à pergunta: Você já se esforçou repetidas vezes para controlar, diminuir ou parar de usar a internet, mas fracassou?\n",
    'LM': "Resposta do usuário à pergunta: Você fica inquieto, mal-humorado, deprimido ou irritável quando tenta diminuir, parar de usar a internet ou quando o uso é restringido?\n",
    'LN': "Resposta do usuário à pergunta: Você fica online mais tempo do que pretendia originalmente?\n",
    'LO': "Resposta do usuário à pergunta: Você já prejudicou ou correu o risco de perder um relacionamento significativo, emprego ou oportunidade educacional ou profissional por causa de internet?\n",
    'LP': "Resposta do usuário à pergunta: Você já mentiu para familiares, terapeutas ou outras pessoas para esconder a extensão do seu envolvimento com a internet?\n",
    'LQ': "Resposta do usuário à pergunta: Você usa a internet como uma maneira de fugir de problemas ou de aliviar um humor desagradável (por exemplo, sentimento de impotência, solidão, culpa, tristeza, ansiedade, depressão)?\n",
    'LR': "Momento em que começou a responder a tela 71 do Questionário:\n",
    'LS': "Resposta do usuário à pergunta: Com que frequência você consome Cafeina?\n",
    'LT': "Resposta do usuário à pergunta: Com que frequência você consome Álcool?\n",
    'LU': "Resposta do usuário à pergunta: Com que frequência você consome Tabaco?\n",
    'LV': "Resposta do usuário à pergunta: Com que frequência você consome Maconha?\n",
    'LW': "Resposta do usuário à pergunta: Com que frequência você consome Cocaína/crack?\n",
    'LX': "Momento em que começou a responder a tela 72 do Questionário\n",
    'LY': "Resposta do usuário à pergunta: Você tem medo ou ansiedade acentuados acerca de um objeto ou situação (p. ex., voar, altura, animais, tomar uma injeção, ver sangue).\n",
    'LZ': "Resposta do usuário à pergunta: Você apresenta dificuldade persistente de descartar ou de se desfazer de pertences, independentemente do seu valor real.\n",
    'MA': "Resposta do usuário à pergunta: Possui medo ou ansiedade acentuada acerca de uma ou mais situações sociais em que é exposto a uma possível avaliação por outras pessoas. Exemplos incluem interações sociais (p. ex., manter uma conversa, encontrar pessoas que não são familiares), ser observado (p. ex., comendo ou bebendo) e situações de desempenho diante de outros (p. ex., proferir palestras, falar em público).\n",
    'MB': "Resposta do usuário à pergunta: Você não tem amigos íntimos ou confidentes que não sejam membros da família de primeiro grau. Geralmente, busca atividades de lazer e/ou profissionais de forma solitária?\n",
    'MC': "Resposta do usuário à pergunta: Você adota um estilo bem baixo de gastos em relação a si e a outros; enxergando o dinheiro como algo a ser poupado para possíveis emergências futuras.\n",
    'MD': "Resposta do usuário à pergunta: Você vem tendo sentimentos de inutilidade ou culpa excessiva?\n",
    'ME': "Resposta do usuário à pergunta: Você iniciou uma quantidade maior de projetos do que o normal ou se envolveu em atividades mais arriscadas do que o habitual?\n",
    'MF': "Momento em que começou a responder a tela 73 do Questionário\n",
    'MG': "Resposta do usuário à pergunta: Você tem Daltonismo?\n",
    'MH': "Momento em que começou a responder a tela 74 do Questionário\n",
    'MI': "Cores que foram pintadas as folhas da arvore que apareceu para o usuário:\n",
    'MJ': "Momento em que começou a responder a tela 75 do Questionário\n",
    'MK': "Cores que foram pintadas nos retângulos que apareceram para o usuário:\n",
    'ML': "Momento em que começou a responder a tela 76 do Questionário\n",
    'MM': "Selecione qual dia da semana é hoje?\n",
    'MN': "Momento em que começou a responder a tela 77 do Questionário\n",
    'MO': "Quanto tempo, aproximadamente, você acha que investiu para fazer este teste?\n",
}

wb = Workbook()
ws = wb.active
ws.title = "Questionário"

for col, texto in comentarios.items():
    partes = texto.strip().split('\n')
    ws[f'{col}1'] = col
    if len(partes) >= 1:
        ws[f'{col}2'] = partes[0].strip()
    for i, linha in enumerate(partes[1:], start=3):
        ws[f'{col}{i}'] = linha.strip()

wb.save("questionario_completo_colunas_B_a_MO.xlsx")
